### ISSUE TITLE
Support deriving functions with labeled arguments

### ISSUE THREAD

**Issue by jobjo** [jobjo/popper#38]
The following is currently not supported:

```ocaml
type t = { run : name:string -> unit -> int } [@@deriving sample] 
```

The problem is the labeled argument `name`.

**Comment by vch9** [comment]
> ```ocaml
> type t = { run : ~name -> unit -> int } [@@deriving sample] 
> ```
Is that type correct ? I don't understand how you can know the type for `~name`

**Comment by jobjo** [comment]
Oops, that was a typo. Updated the description.

**Comment by jobjo** [comment]
Addressed in https://github.com/jobjo/popper/pull/67

**Comment by jobjo** [comment]
Addressed in https://github.com/jobjo/popper/pull/68
