### ISSUE TITLE
Support char, bytes, int32, int64 comparators

### ISSUE THREAD

**Issue by bikallem** [jobjo/popper#47]
Hi,
Thanks for this useful library. I am evaluating `popper` for one of my projects and realized there is no built-in support for `char`, `bytes`, `int32`, `int64` and `unit` data types. Is this by design and if not are you open to PR to add support for this?

**Comment by jobjo** [comment]
Hi, `char`, `int32`, `int64` and `unit` do exist in the `Sample` module. See the [primitives section](https://jobjo.github.io/popper/api/popper/Popper/Sample/index.html#primitives). 

`bytes` (and likely a few others) are missing. Should be straight forward to add. Feel free to push a PR yourself or I will take a  look. I have a few other missing pieces in the pipeline so should push a new version soon.

Let me know if you have any other requests!

**Comment by bikallem** [comment]
> Hi, char, int32, int64 and unit do exist in the Sample module. See the primitives section.

Indeed, `Sample` does have those primitives and it seems to be missing in `Comparator.t`. In terms of using the `Popper.equal` function it seems to require `'a Comparator.t` and not `'a Sample.t`, hence me raising the issue. 

I will send the PR shortly to address this issue.

**Comment by jobjo** [comment]
> Indeed, Sample does have those primitives and it seems to be missing in Comparator.t. In terms of using the Popper.equal function it seems to require 'a Comparator.t and not 'a Sample.t, hence me raising the issue.

Ah, right. Should make sure those line up.

> I will send the PR shortly to address this issue.

Great, thanks!

**Comment by bikallem** [comment]
> bytes (and likely a few others) are missing. Should be straight forward to add. Feel free to push a PR yourself or I will take a look. I have a few other missing pieces in the pipeline so should push a new version soon.

For `bytes` in `Sample.t`, should this just peruse the `String` module implementation?

**Comment by jobjo** [comment]
Arguably the distribution for sampling char values could be made different but I think it's fine to just map over `string`.
