### ISSUE TITLE
Provide array_sample

### ISSUE THREAD

**Issue by copy** [jobjo/popper#54]
The following fails with `Unbound value array_sample`:

```ocaml
  type foo = {
    bar: int array;
  }
  [@@deriving popper]
```

As a temporary work-around, I've used `Sample.list` to define array_sample: 

```ocaml
  let array_sample t = Popper.Sample.map Array.of_list (Popper.Sample.list t)
```

**Comment by jobjo** [comment]
Thanks for reporting. Addressing in https://github.com/jobjo/popper/pull/55

**Comment by jobjo** [comment]
Landed fix. Will be part of next release.
