### ISSUE TITLE
Exception is not caught in Sample.bind

### ISSUE THREAD

**Issue by copy** [jobjo/popper#61]
The following example fails with `Fatal error: exception File "test.ml", line 2, characters 71-77: Assertion failed`:

```ocaml
open Popper
let () = run (test (fun () -> Popper.Sample.bind Sample.bool (fun _ -> assert false)))
```

**Comment by jobjo** [comment]
Hi, I belive this was fixed in https://github.com/jobjo/popper/pull/50. Will soon release a new version.

**Comment by copy** [comment]
I don't think it was properly fixed. I can reproduce this with popper pinned to the latest commit (`opam pin add --dev popper`). It *does* work when removing the `Popper.Sample.bind` above.

**Comment by jobjo** [comment]
Right, exception were only caught at the level of producing a `Random.t Sample.t` not in actually running the sample. Fixed https://github.com/jobjo/popper/pull/63.
