### ISSUE TITLE
Sample.char sometimes fails with Invalid_argument("Char.chr")

### ISSUE THREAD

**Issue by copy** [jobjo/popper#62]
```ocaml
open Popper
open Popper.Sample.Syntax
let () = run ~config:(Config.num_samples 100000000) (test (fun () ->
    let* _ = Sample.char in pass))
```

The high `num_samples` is necessary to reproduce, however it also happens with a lower sample count when sampling multiple chars per test (`char array` in my case).

**Comment by jobjo** [comment]
Thanks for reporting. Will take a look.

**Comment by jobjo** [comment]
Fixed in https://github.com/jobjo/popper/pull/64.
